#!/bin/bash

if !grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    if ! is_installed "code"; then
        echo "installing vscode"
        if [ -f "/etc/redhat-release" ]; then
            sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
            sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

            sudo dnf install -y code
        elif [ -f "/etc/debian_version" ]; then
            sudo apt-get install -y wget gpg
            wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
            sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
            rm -f packages.microsoft.gpg

            sudo apt install -y apt-transport-https
            sudo apt update
            sudo apt install -y code
        fi
    fi
fi

code --install-extension njpwerner.autodocstring
code --install-extension GitHub.copilot
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension VisualStudioExptTeam.vscodeintellicode
