#!/bin/bash
set -e -o pipefail

if ! is_installed "ag"; then
    if [ -f "/etc/redhat-release" ]; then
        install_package the_silver_searcher
    elif [ -f "/etc/debian_version" ]; then
        install_package silversearcher-ag
    fi
fi
